"""empty message

Revision ID: 5f3e4d94b330
Revises: 
Create Date: 2022-12-09 15:34:18.152476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f3e4d94b330'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(length=50), nullable=True),
    sa.Column('smsg', sa.String(), nullable=True),
    sa.Column('account', sa.String(length=64), nullable=True),
    sa.Column('vote', sa.String(), nullable=True),
    sa.Column('balance', sa.String(length=128), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voting')
    # ### end Alembic commands ###
