"""empty message

Revision ID: 6997b663b785
Revises: 5f3e4d94b330
Create Date: 2022-12-09 18:13:25.202769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6997b663b785'
down_revision = '5f3e4d94b330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iplogger',
    sa.Column('numQ', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('where', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('numQ')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('iplogger')
    # ### end Alembic commands ###
